import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {validate,hashDocument,jsonSchemas} from './schema.mjs';import {runImport} from './index.mjs';
const base={schema_version:'1.0',season:2026,week:2,model_version:'handoff-bootstrap-1',generated_at:'2026-09-21T00:00:00.000Z'};
const research={...base,kind:'research',frozen:false,payload:{title:'Handoff connection test',dek:'No research or picks published. Waiting for completed Week 2 research.',games:[],qualifiedProps:[]}};research.content_hash=await hashDocument(research);
const results={...base,kind:'results',research_content_hash:null,payload:{results:[],learning_notes:[]}};results.content_hash=await hashDocument(results);
for(const dir of ['latest','week/2026-W02','schemas'])mkdirSync(new URL('./'+dir+'/',import.meta.url),{recursive:true});
for(const p of [research,results])for(const dir of ['latest','week/2026-W02'])writeFileSync(new URL('./'+dir+'/'+p.kind+'.json',import.meta.url),JSON.stringify(p,null,2)+'\n');
for(const [kind,schema]of Object.entries(jsonSchemas))writeFileSync(new URL('./schemas/'+kind+'.schema.json',import.meta.url),JSON.stringify(schema,null,2)+'\n');
test('strict schema, canonical hash, future timestamp and outcome validation',async()=>{await validate(research,'research');await assert.rejects(validate({...research,week:3},'research'));await assert.rejects(validate({...research,schema_version:'2'},'research'));await assert.rejects(validate({...research,market_data:{}},'research'));const future={...research,generated_at:'2099-01-01T00:00:00Z'};future.content_hash=await hashDocument(future);await assert.rejects(validate(future,'research'));});
test('atomic import, repeat no-op, rollback, frozen protection and results isolation',async()=>{
 const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE sync_state(source TEXT PRIMARY KEY,last_attempt_at TEXT,last_success_at TEXT,next_due_at TEXT,status TEXT,record_count INTEGER DEFAULT 0,last_error TEXT); CREATE TABLE raw_snapshots(id INTEGER PRIMARY KEY,kind TEXT,source TEXT,source_key TEXT,captured_at TEXT,payload_json TEXT); CREATE TABLE market_snapshots(id INTEGER PRIMARY KEY); CREATE TABLE stat_snapshots(id INTEGER PRIMARY KEY,entity_type TEXT,entity_id TEXT,season INTEGER,week INTEGER,source TEXT,captured_at TEXT,payload_json TEXT); CREATE TABLE weekly_research(week_key TEXT PRIMARY KEY,title TEXT,dek TEXT,published_at TEXT,source TEXT,payload_json TEXT);`);
 db.exec(readFileSync(new URL('./migration.sql',import.meta.url),'utf8'));
 let fail=false;const env={GITHUB_REPOSITORY_URL:'https://github.com/davidrogers194/SIGNAL_DATA',GITHUB_BRANCH:'main',DB:{prepare(sql){let args=[];return {bind(...a){args=a;return this},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}}}},async batch(statements){db.exec('BEGIN');try{for(const s of statements){await s.run();if(fail)throw Error('forced rollback')}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}}};
 const docs={research:structuredClone(research),results:structuredClone(results)};const original=globalThis.fetch;globalThis.fetch=async url=>new Response(JSON.stringify(String(url).includes('/commits/')?{sha:'a'.repeat(40)}:{encoding:'base64',content:Buffer.from(JSON.stringify(docs[String(url).includes('research.json')?'research':'results'])).toString('base64')}));
 try{
  assert.equal((await runImport(env)).state,'imported');assert.equal(db.prepare('SELECT count(*) n FROM signal_github_handoff').get().n,2);assert.equal((await runImport(env)).state,'unchanged');assert.equal(db.prepare('SELECT count(*) n FROM weekly_research').get().n,0);
  docs.research.generated_at='2026-09-21T00:01:00.000Z';docs.research.content_hash=await hashDocument(docs.research);fail=true;assert.equal((await runImport(env)).state,'error');assert.equal(db.prepare("SELECT content_hash FROM signal_github_handoff WHERE kind='research'").get().content_hash,research.content_hash);fail=false;
  db.prepare("UPDATE signal_github_handoff SET frozen=1 WHERE kind='research'").run();assert.match((await runImport(env)).error,/frozen/);assert.equal(db.prepare('SELECT count(*) n FROM market_snapshots').get().n,0);
  docs.research=structuredClone(research);docs.results.content_hash='0'.repeat(64);assert.match((await runImport(env)).error,/hash/);
 }finally{globalThis.fetch=original;db.close()}
});
